service: api-evolution

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-dynamodb-local
  - serverless-offline

functions:
  create:
    handler: create.create
    events:
      - http:
        path: evolutions
        method: post
        cors: true 
  list:
    handler: list.list
    events:
      - http:
        path: evolutions
        method: get
        cors: true
  read:
    handler: read.read
    events:
      - http:
          path: evolutions/{id}
          method: get,
          cors: true
  update:
    handler: update.update
    events:
      - http:
        path: evolutions/{id}
        method: put
        cors: true
  delete:
    handler: delete.delete
    events:
      - http:
        path: evolutions/{id}
        method: delete
        cors: true
