  create:
    handler: evolution/create.create
    events:
      - http:
          path: evolutions
          method: post
          cors: true
  list:
    handler: evolution/list.list
    events:
      - http:
          path: evolutions
          method: get
          cors: true
  read:
    handler: evolution/read.read
    events:
      - http:
          path: evolutions/{id}
          method: get
          cors: true
  update:
    handler: evolution/update.update
    events:
      - http:
          path: evolutions/{id}
          method: put
          cors: true
  delete:
    handler: evolution/delete.delete
    events:
      - http:
          path: evolutions/{id}
          method: delete
          cors: true
